-- MySQL Script generated by MySQL Workbench
-- Tue Jan 23 20:42:19 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_p2_web
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_p2_web` ;

-- -----------------------------------------------------
-- Schema db_p2_web
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_p2_web` DEFAULT CHARACTER SET utf8 ;
USE `db_p2_web` ;

-- -----------------------------------------------------
-- Table `db_p2_web`.`Concurso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_p2_web`.`Concurso` ;

CREATE TABLE IF NOT EXISTS `db_p2_web`.`Concurso` (
  `id` BIGINT UNSIGNED NOT NULL,
  `data_sorteio` DATE NOT NULL,
  `arrecadacao_total` FLOAT NOT NULL,
  `estimativa_premio` FLOAT NOT NULL,
  `valor_acumulado_especial` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_p2_web`.`Bola`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_p2_web`.`Bola` ;

CREATE TABLE IF NOT EXISTS `db_p2_web`.`Bola` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `valor` INT NOT NULL,
  `Concurso_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Bola_Concurso_idx` (`Concurso_id` ASC),
  CONSTRAINT `fk_Bola_Concurso`
    FOREIGN KEY (`Concurso_id`)
    REFERENCES `db_p2_web`.`Concurso` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_p2_web`.`Ganhadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_p2_web`.`Ganhadores` ;

CREATE TABLE IF NOT EXISTS `db_p2_web`.`Ganhadores` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `qnt_bolas_acertadas` INT NOT NULL,
  `qnt_ganhadores` INT NOT NULL,
  `rateio` FLOAT NOT NULL,
  `acumulado` FLOAT NULL,
  `Concurso_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Ganhadores_Concurso1_idx` (`Concurso_id` ASC),
  CONSTRAINT `fk_Ganhadores_Concurso1`
    FOREIGN KEY (`Concurso_id`)
    REFERENCES `db_p2_web`.`Concurso` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_p2_web`.`SuperGanhador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_p2_web`.`SuperGanhador` ;

CREATE TABLE IF NOT EXISTS `db_p2_web`.`SuperGanhador` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cidade` VARCHAR(255) NOT NULL,
  `uf` CHAR(2) NOT NULL,
  `Ganhadores_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `iid_UNIQUE` (`id` ASC),
  INDEX `fk_SuperGanhador_Ganhadores1_idx` (`Ganhadores_id` ASC),
  CONSTRAINT `fk_SuperGanhador_Ganhadores1`
    FOREIGN KEY (`Ganhadores_id`)
    REFERENCES `db_p2_web`.`Ganhadores` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
